# prod docker-compose.yml
version: '3.9'

secrets:
  nostr_keys:
    file: ../keys_nsec.txt
  coinapi_keys:
    file: ../keys_coinapi.txt

services:
  nostrboot-btc2poke:
    image: nostrboot-btc2poke
    container_name: nostrboot-btc2poke
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /btc2poke
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - COINAPI_BASE_URL=https://rest.coinapi.io
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - COINAPI_PRIVATE_KEY_FILE=/run/secrets/coinapi_keys
      - NOSTR_RELAYS=wss://nostr.plebchain.org;wss://bitcoiner.social;wss://relay.nostrplebs.com;wss://nostr.relayer.se;wss://relay.nostr.ch;wss://nostr.sandwich.farm;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://relay.snort.social;wss://nostr.bitcoiner.social;wss://atlas.nostr.land;wss://nostr.zebedee.cloud
    tty: true
    secrets:
      - nostr_keys
      - coinapi_keys
