secrets:
  nostr_keys:
    file: ../keys_nsec.txt

services:
  nostrboot-btc2poke:
    image: nostrboot-btc2poke
    container_name: nostrboot-btc2poke
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /btc2poke
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://nos.lol;wss://nostr.mom;wss://relay.damus.io;wss://nostr.animeomake.com
    tty: true
    secrets:
      - nostr_keys
