# prod docker-compose.yml
version: '3.9'

secrets:
  nostr_keys:
    file: ../keys_nsec.txt
  coinapi_keys:
    file: ../keys_coinapi.txt

services:
  nostrboot-btc2poke:
    image: nostrboot-btc2poke
    container_name: nostrboot-btc2poke
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /btc2poke
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - COINAPI_BASE_URL=https://rest.coinapi.io
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - COINAPI_PRIVATE_KEY_FILE=/run/secrets/coinapi_keys
      - NOSTR_RELAYS=wss://nos.lol;wss://nostr.mom;wss://relay.damus.io;wss://offchain.pub;wss://relay.snort.social;wss://relay.mostr.pub;wss://nostr.vulpem.com;wss://nostr.polyserv.xyz;wss://nostr.storymakerapi.fr;wss://nostr.15b.blue;wss://th2.nostr.earnkrub.xyz;wss://n.ok0.org;wss://af.purplerelay.com;wss://nostr.animeomake.com
    tty: true
    secrets:
      - nostr_keys
      - coinapi_keys
