version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

secrets:
  nostr_keys:
    file: ../keys_nsec.txt
  coinapi_keys:
    file: ../keys_coinapi.txt

services:
  nostrboot-btc2poke:
    image: nostrboot-btc2poke
    container_name: nostrboot-btc2poke
    #user: btc2poke
    build:
      context: ./.
      dockerfile: ./Dockerfile
    working_dir: /btc2poke
    volumes:
      - .:/btc2poke:cached
      - node_modules_vol:/btc2poke/node_modules
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - COINAPI_BASE_URL=https://rest.coinapi.io
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - COINAPI_PRIVATE_KEY_FILE=/run/secrets/coinapi_keys
      - NOSTR_RELAYS=wss://relay.nostrica.com;wss://nostr.plebchain.org;wss://relay.nostriches.org;wss://bitcoiner.social;wss://relay.nostrplebs.com;wss://nostr.rocks;wss://nostr.relayer.se;wss://relay.nostr.ch;wss://nostr.sandwich.farm;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://relay.snort.social;wss://nostr.bitcoiner.social;wss://nostr.inosta.cc;wss://puravida.nostr.land;wss://atlas.nostr.land;wss://nostr.milou.lol;wss://brb.io;wss://nostr.zebedee.cloud;wss://nostr.frennet.xyz
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys
      - coinapi_keys