secrets:
  nostr_keys:
    file: keys_nsec_dev.txt

services:
  nostrboot-btc2poke-dev:
    image: nostrboot-btc2poke-dev
    container_name: nostrboot-btc2poke-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /pokeboot
    volumes:
      - ..:/pokeboot:cached
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - NOSTR_RELAYS=wss://nos.lol;wss://nostr.mom;wss://relay.damus.io;wss://nostr.animeomake.com
    tty: true
    secrets:
      - nostr_keys
