version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules

secrets:
  nostr_keys:
    file: keys_nsec_dev.txt
  coinapi_keys:
    file: keys_coinapi_dev.txt

services:
  nostrboot-btc2poke-dev:
    image: nostrboot-btc2poke-dev
    container_name: nostrboot-btc2poke-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile.dev
    working_dir: /pokeboot
    volumes:
      - ..:/pokeboot:cached
      - node_modules_vol:/bater-ponto/node_modules
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - COINAPI_BASE_URL=https://rest.coinapi.io
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - COINAPI_PRIVATE_KEY_FILE=/run/secrets/coinapi_keys
      - NOSTR_RELAYS=wss://nostr.plebchain.org;wss://nostr.rocks;wss://nostr.relayer.se;wss://relay.nostr.ch;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://relay.snort.social;wss://nostr.bitcoiner.social;wss://nostr.inosta.cc;wss://puravida.nostr.land;wss://nostr.milou.lol;wss://brb.io;wss://nostr.zebedee.cloud;wss://nostr.frennet.xyz
      - TZ=America/Sao_Paulo
    tty: true
    secrets:
      - nostr_keys
      - coinapi_keys