version: '3.9'

secrets:
  nostr_keys:
    file: keys_nsec_dev.txt
  coinapi_keys:
    file: keys_coinapi_dev.txt

services:
  nostrboot-btc2poke-dev:
    image: nostrboot-btc2poke-dev
    container_name: nostrboot-btc2poke-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /pokeboot
    volumes:
      - ..:/pokeboot:cached
    environment:
      - APP_JSON_FILE_DATABASE=./last-published-pokemons.json
      - COINAPI_BASE_URL=https://rest.coinapi.io
      - NOSTR_PRIVATE_NSEC_FILE=/run/secrets/nostr_keys
      - COINAPI_PRIVATE_KEY_FILE=/run/secrets/coinapi_keys
      - NOSTR_RELAYS=wss://nostr.plebchain.org;wss://relay.nostriches.org;wss://relay.mostr.pub;wss://nostr-pub.wellorder.net;wss://relay.snort.social;wss://nostr.inosta.cc;wss://nostr.milou.lol;wss://nostr.frennet.xyz;wss://relay.damus.io;wss://nos.lol;wss://nostr.orangepill.dev;wss://offchain.pub;wss://relay.shitforce.one;wss://yabu.me;wss://ear-design-distinct-competition.trycloudflare.com;wss://relayable.org;wss://ca.relayable.org;wss://nostr1.current.fyi;wss://nostr.vulpem.com;wss://nostrich.friendship.tw;wss://n.xmr.se;wss://nostr-1.nbo.angani.co
    tty: true
    secrets:
      - nostr_keys
      - coinapi_keys
